# Site settings
title: MrLoh
email: hi@MrLoh.se
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://MrLoh.se" # the base hostname & protocol for your site
twitter_username: MrLoh
github_username:  MrLoh

# Build settings
safe: true
lsi: false
source: "."
exclude: [node_modules, Gruntfile.coffee, package.json, README.md]

gems:
  - jekyll-redirect-from

jekyll-redirect-from:

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true
excerpt_separator: <!--/-->

sass:
  sass_dir: assets/css

#output settings
permalink: '/:year/:month/:title/'

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Tobias Lohse"
      author-link: /about/
      kudos: true
      comments: true
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      author: "Tobias Lohse"
      author-link: /about/
      kudos: false
      comments: false

kudos_server: 'https://mrloh-kudos-server.herokuapp.com/kudos'
...
