---
title: MrLoh
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: Tobias Lohse
    author-link: "/about/"
    kudos: true
    comments: true
- scope:
    path: ''
    type: drafts
  values:
    layout: post
    author: Tobias Lohse
    author-link: "/about/"
    kudos: false
    comments: false
email: hi@MrLoh.se
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: ''
url: http://MrLoh.se
twitter_username: MrLoh
github_username: MrLoh
safe: true
lsi: false
source: "."
exclude:
- node_modules
- Gruntfile.coffee
- package.json
- README.md
gems:
- jekyll-redirect-from
jekyll-redirect-from: 
markdown: kramdown
kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
excerpt_separator: "<!--/-->"
sass:
  sass_dir: assets/css
permalink: "/:year/:month/:title/"
kudos_server: https://mrloh-kudos-server.herokuapp.com/kudos
